services:
    postgres:
        image: postgres:12
        container_name: postgres
        env_file: .env
        restart: always
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
            interval: 10s
            timeout: 5s
            retries: 5
        volumes:
            - ./data/postgres:/var/lib/postgresql/data
            - ./server/database/migrations:/docker-entrypoint-initdb.d
        ports:
            - ${POSTGRES_PORT}:${POSTGRES_PORT}

    web-app:
        env_file:
            - .env
        environment:
            - IGDB_CLIENT_ID=${IGDB_CLIENT_ID}
            - IGDB_CLIENT_ACESS_TOKEN=${IGDB_CLIENT_ACESS_TOKEN}
        build:
            context: ./
        depends_on:
            postgres:
                condition: service_healthy
        ports:
            - '3000:3000'
        command: ['sh', '-c', 'node .output/server/index.mjs']
