services:
    postgres:
        image: postgres:12
        container_name: postgres
        env_file: .env
        restart: always
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
            interval: 10s
            timeout: 5s
            retries: 5
        volumes:
            - ./data/postgres:/var/lib/postgresql/data
        ports:
            - ${POSTGRES_PORT}:${POSTGRES_PORT}

    web-app:
        env_file:
            - .env
        build:
            context: ./
        depends_on:
            postgres:
                condition: service_healthy
        ports:
            - '3000:3000'
        command:
            [
                'sh',
                '-c',
                'pnpm drizzle-kit push --config drizzle.config.ts && node .output/server/index.mjs'
            ]
