name: Lint
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    check:
        runs-on: ubuntu-latest
        container:
            image: node:22-alpine

        strategy:
            matrix:
                command: [lint, format]

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Setup Node + Corepack + pnpm cache
              uses: actions/setup-node@v3
              with:
                node-version: 22
                cache: pnpm

            - name: Install dependencies
              run: pnpm install

            - name: Run ${{ matrix.command }}
              run: pnpm ${{ matrix.command }}
